language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t diesel457/docker-react -f Dockerfile.dev .

script:
  - docker run diesel457/docker-react npm run test -- --coverage
